### ISSUE TITLE
How do you print to the screen?

### ISSUE THREAD

**Issue by stevevance** [adamwathan/form#34]
I see that I can individually ````echo```` each ````$builder```` form element but is there a way to ````echo```` the whole form?

**Comment by adamwathan** [comment]
Hey Steve! No not really, it's meant to be used right in the template. Being able to create whole form objects and rendering them at once is probably not the direction this will ever go in. I'm usually collaborating with designers or front-end developers who need to be able to access and structure the markup in the template, so that's how this package is meant to be used.

Maybe the Symfony Form component will work well for your workflow? I haven't used it myself but the way I understand it it pushes a lot more to the backend: http://symfony.com/doc/current/book/forms.html

**Comment by stevevance** [comment]
What does the ````->render()```` method on ````->open()```` do?

**Comment by adamwathan** [comment]
Just renders the opening form tag:

https://github.com/adamwathan/form/blob/master/tests/FormOpenTest.php#L12-L19
