### ISSUE TITLE
Feature Request: Support url resolution of controller methods

### ISSUE THREAD

**Issue by nodefortytwo** [adamwathan/form#57]
It would be nice to be able to pass in controller method names or route names such as `Auth\AuthController@postLogin` either into the action method of form open or another method such as route()

`open()->action(action('Auth\AuthController@postSms'))` seems messy

**Comment by adamwathan** [comment]
Hey! Since this package isn't Laravel-only unfortunately I can't easily add this feature. `action` in terms of the attribute on the form element just refers to the endpoint URL, while in Laravel it means a reverse-resolved controller action URL, so I'm not sure what the API would be even if I wanted to add it.

Are you using this package directly or the BootForms extension? Could probably make a light wrapper for this form builder that added support for controller actions and route resolution. Lemme think about it :

**Comment by nodefortytwo** [comment]
I am using the BootForms extension (I didn't know of the basic forms package until I saw the dependency)

I am probably going to have to extend the BootForms lib myself for our specific use case so its not really a big issue, just a nice to have really.

thanks for the great library.
